version: 2
registries:
  nuget-feed-nuget-pkg-github-com-lundalogik-index-json:
    type: nuget-feed
    url: https://nuget.pkg.github.com/lundalogik/index.json
    username: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_LUNDALOGIK_INDEX_JSON_USERNAME}}"
    password: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_LUNDALOGIK_INDEX_JSON_PASSWORD}}"

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  pull-request-branch-name:
    separator: "-"
  registries:
  - nuget-feed-nuget-pkg-github-com-lundalogik-index-json
